// <auto-generated />
namespace CrowdTouring_Projeto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userIdVoto4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userIdVoto4));
        
        string IMigrationMetadata.Id
        {
            get { return "201607051819588_userIdVoto4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
